apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://snowdrop.github.io/cloudflare-webhook'
    targetRevision: 0.3.0
    helm:
      parameters:
        - name: groupName
          value: kallhall.cc
    chart: cloudflare-webhook
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated: {}    