apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externaldns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    targetRevision: 1.14.3
    helm:
      parameters:
        - name: provider.name
          value: godaddy
        - name: txtOwnerId
          value: k0s
        - name: txtPrefix
          value: external-dns.
      values: >-
        extraArgs: ["--default-targets=$(PUBLIC-IP)",
        "--godaddy-api-key=$(API-KEY)", "--godaddy-api-secret=$(API-SECRET)"]
  
        env:
  
        - name: API-KEY
          valueFrom:
            secretKeyRef:
              name: godaddy-api-key
              key: godaddy-api-key
        - name: API-SECRET
          valueFrom:
            secretKeyRef:
              name: godaddy-api-key
              key: godaddy-api-secret
        - name: PUBLIC-IP
          valueFrom:
            configMapKeyRef:
              name: public-ip-config
              key: public-ip
    chart: external-dns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: externaldns
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
