# serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-creator-sa
  namespace: arc-runners

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-creator-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-rolebinding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: secret-creator-sa
  namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: secret-creator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-rolebinding
  namespace: renovate
subjects:
- kind: ServiceAccount
  name: secret-creator-sa
  namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: secret-creator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-rolebinding
  namespace: externaldns
subjects:
- kind: ServiceAccount
  name: secret-creator-sa
  namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: secret-creator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-rolebinding
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: secret-creator-sa
  namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: secret-creator-role
  apiGroup: rbac.authorization.k8s.io
