apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set-renovate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set'
    targetRevision: 0.13.1
    chart: gha-runner-scale-set
helm:
      values: |
        githubConfigUrl: "https://github.com/240snusn"
        githubConfigSecret: "pre-defined-secret"
        controllerServiceAccount:
          namespace: "arc-systems"
          name: "gha-runner-scale-set-controller-gha-rs-controller"
        template:
          spec:
            serviceAccountName: "secret-creator-sa"
            containers:
              - name: runner
                # Use the 'full' tag which is designed for GitHub Actions Runners
                image: ghcr.io/renovatebot/renovate:39.106.0-full
                # No 'command' override is usually needed for the -full image 
                # as it defaults to the runner startup script.
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
