apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.19.2
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
        - name: config.enableGatewayAPI
          value: 'true'
        - name: config.apiVersion
          value: 'controller.config.cert-manager.io/v1alpha1'
        - name: config.kind
          value: 'ControllerConfiguration'
          
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
