apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.cilium.io/'
    targetRevision: 1.18.5
    chart: cilium
    helm:
      values: |
        ignoreDifferences:
          - group: ""
            kind: ConfigMap
            name: hubble-ca-cert
            jsonPointers:
            - /data/ca.crt
          - group: ""
            kind: Secret
            name: hubble-relay-client-certs
            jsonPointers:
            - /data/ca.crt
            - /data/tls.crt
            - /data/tls.key
          - group: ""
            kind: Secret
            name: hubble-server-certs
            jsonPointers:
            - /data/ca.crt
            - /data/tls.crt
            - /data/tls.key

        bgpControlPlane:
          enabled: true
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
              - "10.42.0.0/16"
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_MODULE
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
              - NET_BIND_SERVICE
        kubeProxyReplacement: true
        installCRDs: true
        l7Proxy: true
        l2announcements.enabled: true
        gatewayAPI:
          enabled: true
        ingressController:
          enabled: true
          loadbalancerMode: dedicated
          service:
            loadBalancerIP: "10.1.2.100"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
