apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: hubble-ca-cert
      jsonPointers:
      - /data/ca.crt
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
  sources:
    - repoURL: 'https://helm.cilium.io/'
      chart: cilium
      targetRevision: 1.18.5
      helm:
      values: |
        bgpControlPlane:
          enabled: true
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
              - "10.42.0.0/16"
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_MODULE
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
              - NET_BIND_SERVICE
        kubeProxyReplacement: true
        installCRDs: true
        l7Proxy: true
        l2announcements.enabled: true
        k8sServiceHost: 10.1.1.10
        k8sServicePort: 6443
        gatewayAPI:
          enabled: true
        ingressController:
          enabled: true
          loadbalancerMode: dedicated
          service:
            loadBalancerIP: "10.1.2.100"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
