apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterissuer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/240snusn/homelab
    path: clusterissuer
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
