apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externaldns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    targetRevision: 1.19.0
    helm:
      values: >-
        provider:
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: apiKey
          - name: PUBLIC-IP
            valueFrom:
              configMapKeyRef:
                name: public-ip-config
                key: public-ip
    chart: external-dns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: externaldns
  syncPolicy:
    automated: {} 
    syncOptions:
      - CreateNamespace=true
