apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller'
    targetRevision: 0.13.0
    chart: gha-runner-scale-set-controller
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arc-systems
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
