apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.6.0
    helm:
      values: |
        persistence:
          media:
            enabled: true
            size: 25Gi
            hostPath: /media
            type: hostPath
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
          hosts:
            - host: jellyfin.kallhall.cc
              paths:
                - path: /
                  pathType: Prefix
    chart: jellyfin
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
