apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.6.0
    helm:
      values: |-
        persistence:
          media:
            enabled: true
            size: 25Gi
            hostPath: /media
            nfs:
              server: truenas.lan
              path: /mnt/jellyfin/jellyfin
        ingress:
          enabled: true
          className: cilium
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            io.cilium/lb-ipam-ips: "10.1.2.90"
            ingress.cilium.io/loadbalancer-mode: "dedicated"
          hosts:
            - host: jellyfin.kallhall.cc
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: jellyfin
              hosts:
                - jellyfin.kallhall.cc
    chart: jellyfin
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
