apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.29.1
    chart: pihole
    helm:
      values: |
        podDnsConfig:
          enabled: true
          policy: "None"
          nameservers:
          - 127.0.0.1
          - 1.1.1.1
        serviceWeb:
          type: ClusterIP
          port: 80
        serviceDns:
          mixedService: true
          type: LoadBalancer
          port: 53
          annotations:
            metallb.universe.tf/loadBalancerIPs: "12.12.12.111"  # Replace with your desired IP
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          pathType: Prefix
          hosts:
            - pihole.local  # Replace with your domain
          tls:
            - secretName: pi-hole-tls
              hosts:
                - pihole.local
          ingressClassName: nginx
        admin:
          existingSecret: "pihole-admin"
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
