apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://docs.renovatebot.com/helm-charts'
    targetRevision: 39.220.4
    chart: renovate
    helm:
      values: |
        renovate:
          config: |
            {
              "platform": "github",
              "argocd": {
                "fileMatch": ["appOfApp/.+\\.yaml$"]
              },
              "repositories": ["anton264/homelab"]
            }
          existingConfigFile: false
        envFrom:
          - secretRef:
              name: renovate-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: renovate
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true