apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://docs.renovatebot.com/helm-charts'
    targetRevision: 39.227.2
    chart: renovate
    helm:
      values: |
        renovate:
          config: |
            {
              "platform": "github",
              "argocd": {
                "fileMatch": ["appOfApp/.+\\.yaml$"]
              },
              "repositories": ["240snusn/homelab"],	
              "packageRules": [	
              {	
              "matchUpdateTypes": ["minor", "patch"],	
              "matchCurrentVersion": "!/^0/",	
              "automerge": true
              }
              ]	
              }
          existingConfigFile: false
        envFrom:
          - secretRef:
              name: renovate-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: renovate
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true